// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo1mWJBMVmsNDbrfN7FjICSgB_ewsjwM8',
    appId: '1:348983696638:web:3637d12d19be9df1a999af',
    messagingSenderId: '348983696638',
    projectId: 'found-39d5d',
    authDomain: 'found-39d5d.firebaseapp.com',
    storageBucket: 'found-39d5d.firebasestorage.app',
    measurementId: 'G-JBSTHYNRBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_3_UDcTtCE1vHO5gYQb5HklFFCb6RWc',
    appId: '1:348983696638:android:b4b6197edf0b814aa999af',
    messagingSenderId: '348983696638',
    projectId: 'found-39d5d',
    storageBucket: 'found-39d5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzTW3piJ1OihknqVIlidLCrFG0tc2qUWo',
    appId: '1:348983696638:ios:a89ae5ee61115291a999af',
    messagingSenderId: '348983696638',
    projectId: 'found-39d5d',
    storageBucket: 'found-39d5d.firebasestorage.app',
    iosBundleId: 'com.example.found',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzTW3piJ1OihknqVIlidLCrFG0tc2qUWo',
    appId: '1:348983696638:ios:a89ae5ee61115291a999af',
    messagingSenderId: '348983696638',
    projectId: 'found-39d5d',
    storageBucket: 'found-39d5d.firebasestorage.app',
    iosBundleId: 'com.example.found',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo1mWJBMVmsNDbrfN7FjICSgB_ewsjwM8',
    appId: '1:348983696638:web:fce46a749dcd448ba999af',
    messagingSenderId: '348983696638',
    projectId: 'found-39d5d',
    authDomain: 'found-39d5d.firebaseapp.com',
    storageBucket: 'found-39d5d.firebasestorage.app',
    measurementId: 'G-YVLXW4CJGR',
  );
}
